apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
  labels:
    stage: dev
    project: expense
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0a3554a587bc68ffa
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc
spec:
  storageClassName: ""
  volumeName: ebs-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi          
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    stage: env
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  containers:
  - name: frontend
    image: naresh34/frontend:v1 
    volumeDevices:
    - name: ebs-pv
      devicePath: /usr/share/nginx/html
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: ebs-pvc   
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-service 
  labels:
    stage: env
spec:
  type: LoadBalancer
  selector:
    stage: env
  ports:
    - name: pod-lb
      protocol: TCP
      port: 80
      targetPort: 80
      NodePort: 32000
