apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: naresh-sc
provisioner: ebs.csi.aws.com
reclaimPolicy : Retain
volumeBindingMode:  WaitForFirstConsumer
---
apiVerson: v1
kind: PersistentVolumeClaim
metadata:
  name: naresh-pvc
spec:
  accessModes:
  - ReadWriteOnce
  StorageClassName: naresh-sc
  resources:
    requests:
      storage: 2Gi
---
