apiVersion: v1
kind: PersistentVolume
metadata:
  name: naresh-pv
  labels:
    projectname: naresh-personel
    env: dev
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-08ff8bb32f9f642ab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: naresh-pvc
  labels: 
    projectname: naresh-personel
    env: dev
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
  storageClassName: ""
  volumeName: naresh-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: naresh-pod
  labels:
    projectname: naresh-personel
    env: dev
spec:
  containers:
  - name: naresh-pod1
    image: naresh34/frontend:v1
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: naresh-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: naresh-service
spec:
  type: LoadBalancer
  selector:
    projectname: naresh-personel
    env: dev
  ports:
  - name: naresh-service1
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32001          