apiVersion: v1
kind: PersistentVolume
metadata:
  name: naresh-pv
  labels:
    project: expense
    env: dev
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: ""  # Empty for no StorageClass
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e5992ad2e4f4ee2f  # volume-id
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: naresh-pvc
  labels: 
    project: expense
    env: dev   
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests: 
      storage: 1Gi
  volumeName: naresh-pv
  storageClassName: ""  # Empty for no StorageClass
---
apiVersion: v1
kind: Pod
metadata:
  name: naresh-pod
  labels: 
    project: expense
    env: dev
spec:
  containers:
  - name: naresh-pod
    image: naresh34/tomcat:v1
    volumeMounts: 
    - name: naresh-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: naresh-data
    persistentVolumeClaim:
      claimName: naresh-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: naresh-service
spec:
  selector:
    project: expense
  type: NodePort
  ports:
  - name: naresh-service
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32003
