apiVersion: v1
kind: Pod
metadata:
  name: expense1
  # Namespace: expense
  labels:
    env: dev
    project: expense
    module: frontend
spec:
  containers:
  - name: naresh-pod1
    image: naresh34/frontend:v1
    ports: 
    - containerPort: 80      

# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
# spec:
#   containers:
#   - name: nginx
#     image: nginx:1.14.2
#     ports:
#     - containerPort: 80