apiVersion: v1
kind: pod
metadata:
  name: nginx
  labels:
    stage: dev
    author: naresh
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      containerPorts:
      - 80
  - name: nginx
  image: nginx
  ports:
    containerPorts:
    - 80    