apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    stage: dev
    author: naresh
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80   

    # apiVersion: v1
# kind: Pod
# metadata:
#   name: expense2
#   labels:
#     stage: dev
#     project: expense
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     ports:
#     - containerPort: 80
#   - name: postgres
#     image: naresh34/postgres:v1
#     ports:
#     - containerPort: 5432 