apiVersion: v1
kind: Pod
metadata:
  name: env
  labels:
    env: dev
    author: naresh
  annotations: 
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: learning
      value: devops
    - name: k8-tool      
      value: k8s