apiVersion: v1
kind: Pod
metadata:
  name: nareshnidu1
  labels:
    name: naresh
    status: learning
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    requests:
      cpu: 60m
      memory: 60mi
    limits:
      cpu: 100m
      memory: 100mi  
