apiVersion: v1
kind: Pod
metadata:
  name: nareshnaidu1
  labels:
    name: naresh
    status: learning
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: "60m"
        memory: "60Mi"
      limits:
        cpu: "100m"
        memory: "100Mi"  
