apiVersion: v1
kind: Pod
metadata: 
  name: pod-config
  labels: 
    stage: dev
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 60m
        memory: 80Mi
      limits:
        cpu: 80m
        memory: 100Mi
    env:
    - name: course
      valueFrom:
        configMapRefKey:
          name: naresh-config
          value: course
    - name: status
      valueFrom:
        configMapRefKey:
          name: naresh-config
          value: status       