apiVersion: v1
kind: Pod
metadata:
  name: naresh-pod2
  labels:
    stage: dev
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: naresh-secret
          key: username
    - name: password
      valueFrom: 
        secretKeyRef:
          name: naresh-secret
          key: password      