# apiVersion: v1
# kind: Service
# metadata: 
#   name: naresh-service
# spec:
#   selector:
#     env: dev
#     project: expense
#     module: frontend
#   ports:
#   - name: nginx-svc-port
#     protocol: TCP
#     port: 80
#     targetPort: 80


apiVersion: v1
kind: Service
metadata: 
  name: naresh-service
spec:
  selector:
    stage: dev
    author: naresh
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80

