apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: naresh-frontend
  labels:
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 2
  # these labels are used to select pod and create replicas
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: naresh34/frontend:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: naresh-service-cluster
spec:
  type: NodePort
  selector:
    tier: frontend
  ports:  
  - name: nginx
    protocol: TCP
    port: 80
    targetPort: 80
           