apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: naresh34/frontend:v1
        resources:
          requests:
            cpu: 80m
            memory: 80Mi
          limits:
            cpu: 100m
            memory: 100Mi  
---
apiVersion: v1
kind: Service
metadata:
  name: naresh-deployment
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: naresh-nginx
      protocol: TCP
      port: 80
      targetPort: 80 
      nodePort: 32002
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-demo-deployment
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: hpa-demo-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 10