apiVersion: apps/v1
kind: Deployment
metadata:
  name: naresh-deployment
  labels:
    app: naresh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: naresh
  template:
    metadata:
      labels:
        app: naresh
    spec:
      containers:
      - name: nginx
        image: naresh34/frontend:v1
        ports:
        - containerPort: 80
        resources:
          requests: 
            cpu: 80m
            memory: 100Mi
          limits:
            cpu: 85m
            memory: 120Mi  
---
apiVersion: v1
kind: Service
metadata:
  name: naresh-service
  labels:
    app: naresh
spec:
  selector:
    app: naresh
  ports:
  - name: naresh
  protocol: TCP
  port: 80
  containerPort: 80
  nodePort: 32001
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-demo-deployment
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: naresh-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 5